# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/weedcrop',
                'doc_host': 'https://gpetrousov.github.io',
                'git_url': 'https://github.com/gpetrousov/weedcrop',
                'lib_path': 'weedcrop'},
  'syms': { 'weedcrop.dataset': { 'weedcrop.dataset.create_dataset_list': ('dataset.html#create_dataset_list', 'weedcrop/dataset.py'),
                                  'weedcrop.dataset.create_image_file_list': ('dataset.html#create_image_file_list', 'weedcrop/dataset.py'),
                                  'weedcrop.dataset.create_labels_file_list': ( 'dataset.html#create_labels_file_list',
                                                                                'weedcrop/dataset.py'),
                                  'weedcrop.dataset.find_min_dim': ('dataset.html#find_min_dim', 'weedcrop/dataset.py'),
                                  'weedcrop.dataset.print_ds_info': ('dataset.html#print_ds_info', 'weedcrop/dataset.py')},
            'weedcrop.evaluation': { 'weedcrop.evaluation.calculate_accuracy': ( 'evaluation.html#calculate_accuracy',
                                                                                 'weedcrop/evaluation.py'),
                                     'weedcrop.evaluation.evaluate': ('evaluation.html#evaluate', 'weedcrop/evaluation.py')},
            'weedcrop.features': { 'weedcrop.features.extract_hog_features': ('features.html#extract_hog_features', 'weedcrop/features.py'),
                                   'weedcrop.features.extract_lbp_features': ('features.html#extract_lbp_features', 'weedcrop/features.py'),
                                   'weedcrop.features.feature_fusion': ('features.html#feature_fusion', 'weedcrop/features.py')}}}
