# AUTOGENERATED! DO NOT EDIT! File to edit: ../notebooks/03_features.ipynb.

# %% auto 0
__all__ = ['project_root', 'extract_hog_features', 'extract_lbp_features']

# %% ../notebooks/03_features.ipynb 1
import sys
import os

# Path to the project root (one level above notebooks/)
project_root = os.path.abspath("..")

# Add to Python path
sys.path.append(project_root)

import weedcrop.dataset as weedcrop_ds
import cv2
from skimage.feature import hog, local_binary_pattern

# %% ../notebooks/03_features.ipynb 4
def extract_hog_features(ds):
    
    X_hog_features, y_hog_labels = [], []
    min_width, min_height = weedcrop_ds.find_min_dim(ds)
    
    for i in range(len(ds)):
        img = cv2.imread(ds[i][0])
        img_resized = cv2.resize(img, (min_width, min_height))
        img_gray = cv2.cvtColor(img_resized, cv2.COLOR_BGR2GRAY)

        hog_features = hog(
            img_gray,
            orientations=9,
            pixels_per_cell=(8, 8),
            cells_per_block=(2, 2),
            visualize=False
        )

        # Collect features and labels
        X_hog_features.append(hog_features)
        y_hog_labels.append(ds[i][1])
    return X_hog_features, y_hog_labels

# %% ../notebooks/03_features.ipynb 9
def extract_lbp_features(ds):
    
    X_lbp_features, y_lbp_labels = [], []
    min_width, min_height = weedcrop_ds.find_min_dim(ds)
    
    for i in range(len(ds)):
        img = cv2.imread(ds[i][0])
        img_resized = cv2.resize(img, (min_width, min_height))
        img_gray = cv2.cvtColor(img_resized, cv2.COLOR_BGR2GRAY)

        lbp = feature.local_binary_pattern(img_gray, P=8, R=1, method='uniform')
        lbp_hist, _ = np.histogram(lbp.ravel(), bins=np.arange(0, 11), density=True)        

        # Collect features and labels
        X_lbp_features.append(lbp_hist)
        y_lbp_labels.append(ds[i][1])
    return X_lbp_features, y_lbp_labels
